chmod +x /code/pentest/simple_enum4linux.sh 
chmod +x /code/pentest/simple_sqlmap.sh
chmod +x /code/pentest/simple_ffuf.sh
chmod +x /code/pentest/simple_netcat.sh 
chmod +x /code/pentest/simple_searchsploit.sh
chmod +x /code/pentest/simple_nmap.sh
chmod +x /code/osint/lookup_db.sh
chmod +x /code/osint/lookup_num.sh
chmod +x simple_scripting.sh
chmod +x main_osint.sh
chmod +x main_pentest.sh
pip install requests
